module.exports = {
    "week0": [
        {question:"What has two hands and twelve numbers?",answer:"clock",hint:"This is your first hint",extra_hint:"This is your extra hint"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
    ],
    "week1": [
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
    ],
    "week2": [
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
    ],
    "week3": [
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
    ],
    "week4": [
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
    ],
    "week5": [
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
    ],
    "week6": [
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"Wednesday Question",answer:"clock"},
        {question:"Thursday Question",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
        {question:"What has two hands and twelve numbers?",answer:"clock"},
    ],
    "week7": [
        {question:"Sunday Question",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Monday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Tuesday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Wednesday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Thursday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Friday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Saturday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
    ],
    "week8": [
        {question:"Sunday Question",answer:"time", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Monday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Tuesday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Wednesday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Thursday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Friday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
        {question:"Saturday Question?",answer:"clock", first_hint:'This is your first hint', second_hint:'This is your second hint'},
    ]
}